version: '3.9'
services:
  mysql:
    container_name: mysql_foot_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=foot_club
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    image: mysql
  api:
    container_name: api_nest_foot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/srv/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: "mysql"
    ports:
      - "3000:3000"